sudo: required
services:
  - docker
env:
  - NPM_TARGET=test
  - NPM_TARGET=lint
  - NPM_HELLOWORLD=abc
  - NPM_HELLOWORLD=def

before_install:
  - docker pull node:8-onbuild
install:
  - docker build -t probot-hello .

script:
  - docker run --rm probot-hello npm run $NPM_TARGET 
  - echo "#NPM_HELLOWORLD"

after_success:
  - set -x -v;
    set -e;
    if ["$NPM_TARGET" = "test"]; then 
      docker tag probot-hello probot-hello:$(git rev-parse HEAD);
    else
      echo "Skipping docker tag";
    fi;
    docker images;
    set +x +v;